Refined wrapper, with conditional filter actions.  - Legacy-Id: 37

diff --git a/wrapper b/wrapper
--- a/wrapper
+++ b/wrapper
@@ -5,10 +5,13 @@ version="0.41.0"
 # --- Configuration variables ---
 
 # the filter executable:
-FILTER_BIN=/usr/local/bin/postconfirmc
+FILTER_BIN=/usr/bin/postconfirmc
 
 # Mailman's distributed mailman executable:
 MAILMAN_BIN=/usr/lib/mailman/mail/mailman
+
+# Mail handler executable
+SENDMAIL_BIN=/usr/sbin/sendmail
 
 # Where we store mailman commands identified as spam
 SPAM_STASH=/a/postconfirm/cache
@@ -16,14 +19,19 @@ SPAM_STASH=/a/postconfirm/cache
 # --- Re-invoke with logging ---
 if [ "$RUNNING" != "$0" ]; then
    export RUNNING=$0
-   $0 "$@" 2>&1 | logger -i -t postconfirmw
+   $0 "$@" 2>&1 | logger -t postconfirmw
    exit ${PIPESTATUS[0]}
 fi
 
 # Command line arguments
+## The 'action' argument is set by the caller.  Mailman will set 'action' to one
+## of "post", "owner", or "admin".  The postfix group-alias and draft-alias lists
+## will set 'action' to "filter".
 action="$1"
 dest="$2"
 domain="$3"
+
+[ "$domain" ] || domain=${RECIPIENT##*@}
 
 # Debug switch
 DEBUG=""
@@ -39,6 +47,7 @@ function die() {
 # ----------------
 function note() { 
     [ "$DEBUG" ] && echo -e "$*"
+    logger -i -p user.info -t postconfirmw "$*"
 }
 
 # --- Start of script proper ---
@@ -65,7 +74,7 @@ RECV_LOCALPART=${RECIPIENT%@*}
 if [ "${SEND_LOCALPART##*-}" = "bounces" -a "${RECV_LOCALPART##*-}" = "owner" ]; then
     note "Mailman response piped directly to mailman"
     $MAILMAN_BIN "$action" "$dest"
-elif [ "$action" = post -o "$action" = owner -o "$action" = admin ]; then
+elif [ "$action" = post -o "$action" = owner -o "$action" = admin -o "$action" = filter ]; then
     # Using a temp file to hold the message isn't pretty, but we need to catch the exit
     # code from tmda_filter to decide whether to pipe stuff into mailman or not, and
     # neither $? or $PIPESTATUS[0] lets us do that inside the pipe itself.
@@ -73,13 +82,17 @@ elif [ "$action" = post -o "$action" = owner -o "$action" = admin ]; then
     out=$(mktemp -t postconfirm-out-XXXXXX)
     err=$(mktemp -t postconfirm-err-XXXXXX)
 
-    # Add List-Id: so that we're able to calculate the Archived-At: header later.
-    # This will be overwritten by Mailman during its processing.
-    cat - | formail -I "List-ID: <$dest.ietf.org>" > $tmp
+    if [ "$action" = filter ]; then
+	cat - > $tmp
+    else
+	# Add List-Id: so that we're able to calculate the Archived-At: header later.
+	# This will be overwritten by Mailman during its processing.
+	cat - | formail -I "List-ID: <$dest.ietf.org>" > $tmp
+    fi
 
-    note "Input piped to postconfirm"
-    $FILTER_BIN < $tmp >$out 2>$err
-    errnum=$?
+    note "Input piped to postconfirm: '$FILTER_BIN confirm'"
+    $FILTER_BIN confirm < $tmp 2>$err | /a/postconfirm/insert_expanded_headers "$dest" > $out
+    errnum=${PIPESTATUS[0]}
     
     if [ "$DEBUG" ]; then
 	echo "--- $(date +%Y-%m-%d_%H:%M): $* [$SENDER => $RECIPIENT] ---"	>> /tmp/postconfirm-debug.log
@@ -87,14 +100,24 @@ elif [ "$action" = post -o "$action" = owner -o "$action" = admin ]; then
     fi
 
     if   [ $errnum == 0 ]; then
-	note "Input forwarded to mailman"
-	$MAILMAN_BIN "$action" "$dest" < $out
+	if [ "$action" = filter ]; then
+	    note "Input forwarded to MTA ($SENDMAIL_BIN -f $SENDER $dest@$domain)"
+	    $SENDMAIL_BIN -f "$SENDER" "$dest@$domain" < $out
+	else
+	    note "Input forwarded to mailman ($MAILMAN_BIN $action $dest)"
+	    $MAILMAN_BIN "$action" "$dest" < $out
+        fi
     elif [ $errnum == 1 ]; then
 	note "Error return $errnum from $FILTER_BIN -- not forwarding"
 	[ "$DEBUG" ] && cat $err
     else
-	echo "$FILTER_BIN failure (error $errnum) -- input forwarded to mailman"
-	$MAILMAN_BIN "$action" "$dest" < $tmp
+	if [ "$action" = filter ]; then
+	    echo "$FILTER_BIN failure (error $errnum) -- input forwarded to MTA"
+	    $SENDMAIL_BIN -f "$SENDER" "$dest@$domain" < $tmp
+	else
+	    echo "$FILTER_BIN failure (error $errnum) -- input forwarded to mailman"
+	    $MAILMAN_BIN "$action" "$dest" < $tmp
+	fi
     fi
     [ "$DEBUG" ] || rm -f $tmp $out $err
 else
